export const MOCK_COMPARISON_DATA = {
  product: {
    id: "prod_1",
    name: "Apple iPhone 15 128GB Black",
    brand: "Apple",
    model: "iPhone 15",
    category: "Smartphones",
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600",
    specifications: {
      Display: "6.1-inch Super Retina XDR OLED",
      Processor: "A16 Bionic chip",
      "Rear Camera": "48MP + 12MP dual camera",
      "Front Camera": "12MP TrueDepth",
      Battery: "3,227 mAh",
      Storage: "128GB",
      RAM: "6GB",
      OS: "iOS 17",
      Connectivity: "5G, Wi-Fi 6, Bluetooth 5.3",
      Dimensions: "147.6 x 71.6 x 7.8 mm",
      Weight: "171g",
      Colors: "Black, Blue, Pink, Yellow, Green",
    },
    reviewSummary: "The iPhone 15 delivers excellent performance with its A16 Bionic chip and improved 48MP camera system. USB-C charging is a welcome addition. Battery life is adequate but not class-leading.",
  },
  stores: [
    {
      id: "store_1",
      name: "Amazon",
      slug: "amazon",
      logoUrl: "/stores/amazon.svg",
      price: 67999,
      originalPrice: 79900,
      currency: "INR",
      inStock: true,
      rating: 4.5,
      reviewCount: 12847,
      deliveryDays: 2,
      deliveryFee: 0,
      productUrl: "https://www.amazon.in",
      affiliateUrl: "https://www.amazon.in?tag=priceradar-21",
      cashback: 0,
      emiAvailable: true,
      lowestPrice: true,
    },
    {
      id: "store_2",
      name: "Flipkart",
      slug: "flipkart",
      logoUrl: "/stores/flipkart.svg",
      price: 68999,
      originalPrice: 79900,
      currency: "INR",
      inStock: true,
      rating: 4.4,
      reviewCount: 8923,
      deliveryDays: 3,
      deliveryFee: 0,
      productUrl: "https://www.flipkart.com",
      affiliateUrl: "https://www.flipkart.com?affid=priceradar",
      cashback: 500,
      emiAvailable: true,
      lowestPrice: false,
    },
    {
      id: "store_3",
      name: "Croma",
      slug: "croma",
      logoUrl: "/stores/croma.svg",
      price: 71990,
      originalPrice: 79900,
      currency: "INR",
      inStock: true,
      rating: 4.3,
      reviewCount: 2341,
      deliveryDays: 5,
      deliveryFee: 0,
      productUrl: "https://www.croma.com",
      affiliateUrl: "https://www.croma.com",
      cashback: 0,
      emiAvailable: true,
      lowestPrice: false,
    },
    {
      id: "store_4",
      name: "Reliance Digital",
      slug: "reliance",
      logoUrl: "/stores/reliance.svg",
      price: 72990,
      originalPrice: 79900,
      currency: "INR",
      inStock: false,
      rating: 4.1,
      reviewCount: 1205,
      deliveryDays: 7,
      deliveryFee: 0,
      productUrl: "https://www.reliancedigital.in",
      affiliateUrl: "https://www.reliancedigital.in",
      cashback: 1000,
      emiAvailable: true,
      lowestPrice: false,
    },
    {
      id: "store_5",
      name: "Tata Cliq",
      slug: "tatacliq",
      logoUrl: "/stores/tatacliq.svg",
      price: 69990,
      originalPrice: 79900,
      currency: "INR",
      inStock: true,
      rating: 4.2,
      reviewCount: 3876,
      deliveryDays: 4,
      deliveryFee: 0,
      productUrl: "https://www.tatacliq.com",
      affiliateUrl: "https://www.tatacliq.com",
      cashback: 750,
      emiAvailable: false,
      lowestPrice: false,
    },
  ],
  priceHistory: [
    { date: "2024-01-01", price: 79900 },
    { date: "2024-02-01", price: 76900 },
    { date: "2024-03-01", price: 74900 },
    { date: "2024-04-01", price: 74900 },
    { date: "2024-05-01", price: 71900 },
    { date: "2024-06-01", price: 69900 },
    { date: "2024-07-01", price: 67999 },
  ],
};

export const TRENDING_PRODUCTS = [
  {
    id: "1",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=300",
    lowestPrice: 109999,
    originalPrice: 134999,
    currency: "INR",
    stores: 5,
    discount: 19,
    category: "Smartphones",
  },
  {
    id: "2",
    name: "Sony WH-1000XM5 Headphones",
    brand: "Sony",
    imageUrl: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=300",
    lowestPrice: 24990,
    originalPrice: 34990,
    currency: "INR",
    stores: 4,
    discount: 29,
    category: "Audio",
  },
  {
    id: "3",
    name: "Apple MacBook Air M3",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=300",
    lowestPrice: 114900,
    originalPrice: 134900,
    currency: "INR",
    stores: 3,
    discount: 15,
    category: "Laptops",
  },
  {
    id: "4",
    name: "OnePlus 12 256GB",
    brand: "OnePlus",
    imageUrl: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=300",
    lowestPrice: 53999,
    originalPrice: 64999,
    currency: "INR",
    stores: 4,
    discount: 17,
    category: "Smartphones",
  },
  {
    id: "5",
    name: "Dyson V15 Detect",
    brand: "Dyson",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300",
    lowestPrice: 49900,
    originalPrice: 64900,
    currency: "INR",
    stores: 3,
    discount: 23,
    category: "Home Appliances",
  },
  {
    id: "6",
    name: "iPad Pro 11-inch M4",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=300",
    lowestPrice: 99900,
    originalPrice: 119900,
    currency: "INR",
    stores: 4,
    discount: 17,
    category: "Tablets",
  },
];

export const BLOG_POSTS = [
  {
    id: "1",
    title: "Best Smartphones Under ₹20,000 in 2024",
    excerpt: "Find the best value-for-money smartphones with great cameras and long battery life.",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
    category: "Smartphones",
    readTime: "5 min read",
    slug: "best-smartphones-under-20000",
  },
  {
    id: "2",
    title: "Top 10 Laptops for Students 2024",
    excerpt: "Lightweight, powerful, and budget-friendly laptops perfect for college students.",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
    category: "Laptops",
    readTime: "8 min read",
    slug: "best-laptops-for-students",
  },
  {
    id: "3",
    title: "Smart Watches Under ₹10,000",
    excerpt: "The best feature-packed smartwatches that won't break the bank.",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
    category: "Wearables",
    readTime: "6 min read",
    slug: "best-smartwatches-under-10000",
  },
];
